### ISSUE TITLE
画像の管理

### ISSUE THREAD

**Issue by tronperidot** [tamakon/junk-t#1]
ロゴ画像をどこで管理するか。

- githubに画像を置くのはいやだ。
- firebaseの時はあげ直すたびにurlが変わっていたのでデプロイし直しが発生する・・・

**Comment by takashi1coq** [comment]
直接サーバに画像デプロイする？他の方法があれば。。

**Comment by tronperidot** [comment]
いっそ管理サイト作っちゃうか〜〜〜
という考えも

**Comment by takashi1coq** [comment]
画像の管理はDBでしたっけ？ホワイトボードの内容が思い出せない

**Comment by tronperidot** [comment]
最終的にはDjangoの流儀でって思いつつ、ファイルで勧めていく感じでやってるかな。

**Comment by tronperidot** [comment]
今回はサーバを借りて、Djangoのapi経由で実ファイルをストレージに保存する方針で進めることになった。
