### ISSUE TITLE
[WIP]アプリケーションの実行構成について再考したい

### ISSUE THREAD

**Issue by tronperidot** [tamakon/junk-t#10]
### 概要

現状の構想だといくつか追加で行わないと行けない作業があると考え、シンプルに行かないと思った。
現状の方針のまま進めて問題ないか、他にいいやり方があるのかなど話し合いたい。

### 詳細

今構想していたのは、
1. Django上にstaticファイルを読み込める口を用意する
1. react-create-appのbuildコマンドでDjangoApp/static内に成果物を入れる
1. Djangoのアプリを起動

という考え。

このやり方ではbuild生成物を書き換えることをしないとDjango上では完全にファイルを読み込むことができないように感じている。

### WIP
Djangoのこととかは全然分からないので想像している事は問題でもないかもしれないし、もう少しDjangoのことを理解してから検討したい。

**Comment by h-haraguchi** [comment]
> このやり方ではbuild生成物を書き換えることをしないとDjango上では完全にファイルを読み込むことができないように感じている。

build成果物を書き換えなきゃいけない理由が知りたいな。どんな書き換えが必要なの？

**Comment by tronperidot** [comment]
実際にDjango上で動かせたわけじゃないから推測混じりになっちゃうんだけど。

今って、ReactAppが作る成果物はindex.htmlからなんだけど、
そいつらをstaticディレクトリに移して試してみたらjsファイルが読み込まれなかったのね。
読み込ませるためには、srcの文字列をload staicとかで結合させなきゃいけないのかなって思ったんだ

**Comment by h-haraguchi** [comment]
成果物のindex.htmlの中にあるjsのパスがどうなってるか気になるな。てか俺もreact-create-appちょっとみてみよう。

**Comment by tronperidot** [comment]
```html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <meta name="theme-color" content="#000000">
  <link rel="manifest" href="/manifest.json">
  <link rel="shortcut icon" href="/favicon.ico">
  <title>React App</title>
  <link href="/static/css/main.29266132.css" rel="stylesheet">
</head>

<body>
  <noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
  <script type="text/javascript" src="/static/js/main.e69833ab.js"></script>
</body>

</html>
```

**Comment by h-haraguchi** [comment]
react-create-appのreadmeにこんな記述あった。

> If you need to integrate React code with a server-side template framework like Rails or Django, or if you’re not building a single-page app, consider using nwb, or Neutrino which are more flexible. For Rails specifically, you can use Rails Webpacker.

nwbとかNeutrinoが鍵になりそう？
てかニュートリノってww

**Comment by h-haraguchi** [comment]
そーすみたかんじDjangoのstatic配下にあればアクセス出来そうな感じするけどねぇ。

**Comment by tronperidot** [comment]
> nwbとかNeutrino
これ調べてみるわー

たとえば、静的ファイルを参照しに行こうとしても、apiのアドレスにマッチしてそっちの処理に全部持って行かれるとかってないのかな。

**Comment by h-haraguchi** [comment]
デフォルトだと、staticリソースのパスは/static/だと思われるから、apiのパスを/staticから始めなければマッチすることはないと思うがね。

**Comment by h-haraguchi** [comment]
とりあえず、init-server-appとinit-client-
appをmasterにマージしますか？

**Comment by tronperidot** [comment]
ああごめんなさい、パスが誤っていた。

```
APP_ROOT/templates/screen/static
```
にファイルを展開していたけど、
```
APP_ROOT/screen/static
```
に展開するのが正しかったのか。
これでjsとcssファイルは読み込めるようになった。

**Comment by tronperidot** [comment]
> とりあえず、init-server-appとinit-client-appをmasterにマージしますか？

しよう！

**Comment by h-haraguchi** [comment]
すまん。俺が作ったhtmlだけはtemplateに入れてたんだ。何でtemplateのhtmlだけappに依存しないのかは俺もまだわかってない。

**Comment by h-haraguchi** [comment]
jsとcss読み込めるようになったから実行構成は変えなくてもオッケー？

**Comment by tronperidot** [comment]
構成自体はDjango上に乗せるのまま進めるでオッケーだと思います！
乗せる手順についての検討をissueに起票したのでこれは閉じます。
