### ISSUE TITLE
admin権限について

### ISSUE THREAD

**Issue by takashi1coq** [tamakon/junk-t#13]
先の話になるだろうけどadminができることは

①画像のアップロード
②文言の変更
③上記をもとにhtmlの更新

のつもりで、これを実施するのにreactで管理ページ作成した方がよいのか、djangoのadmin使用した方がよいのか、そもそもこれじゃシンプルに作れない（めんどくさい）のか確認したい。

あと、djangoのadminをそのまま使う場合のデメリットがいまいち理解できてない。セキュリティの問題とかなら新しく作るべきだと思う

**Comment by h-haraguchi** [comment]
djangoでのadminの場合はまず画像アップロードできるのか調べる必要があるね。

**Comment by tronperidot** [comment]
> あと、djangoのadminをそのまま使う場合のデメリットがいまいち理解できてない。セキュリティの問題とかなら新しく作るべきだと思う

reactで管理ページを作ろうかって話は、Djangoが自動生成できることを忘れていたからなのでそんな無い気がするｗ
あるとしたら以下かな
- reactの学習機会が減る
- Djangoが自動生成したものなので、変更の柔軟性が低い恐れがあるやってみないとわからない

メリットは
- 楽
- はやい

かな？ｗ

**Comment by takashi1coq** [comment]
なるほど。
画像のアップロードはadminがやるべきだとおもうから、柔軟性のあるなしで選ぶことにしましょう

> djangoでのadminの場合はまず画像アップロードできるのか調べる必要があるね。

神の方針で

**Comment by h-haraguchi** [comment]
https://docs.djangoproject.com/ja/2.1/ref/models/fields/#imagefield
こんなんあった。ModelのFieldとして定義できるのであればadminでも操作できるってことやね。
しかも、サーバ上の特定のディレクトリにちゃんとファイルをアップロードしてくれるという至れり尽くせりな仕様w

**Comment by tronperidot** [comment]
いいね
このまま簡単にDjango上で画像周りを扱えるみたいだから管理サイトはDjango adminでいい感じかな。
もっと後でいいけどファイルの形式と保存先も考えないとだなあ

**Comment by tronperidot** [comment]
Djangoの管理サイトを現状利用して進めているのでクローズ
