### ISSUE TITLE
Django上にフロントの成果物を乗せる手段を考える

### ISSUE THREAD

**Issue by tronperidot** [tamakon/junk-t#14]
#10 の続き。
Django上でreactを動かすことは確認できたが、Djangoの上に乗せるのに、Templatesの中にindex.htmlを入れて、js, css類はstaticの中に入れてと、手間が掛かるやり方となっている。
できれば1コマンドとかで済むようにしたいので簡略された方法はないか調べる。

フロント側はまず、nwbとかNeutrinoとかを調べてみる。

**Comment by h-haraguchi** [comment]
Djangoのドキュメント読み進めてるんだが、Django側で静的ファイルの参照先決められるらしいから、移動させる必要ないかも。

**Comment by tronperidot** [comment]
そんときって、パスもindexのurlでindex.htmlを呼べる感じなのかな？
それともscreen/index.htmlみたいなimageのパスになるんかな

**Comment by h-haraguchi** [comment]
まず前提としてDjangoでは静的ファイルを同一サーバで配布することを推奨していないらしいw
https://docs.djangoproject.com/en/2.1/howto/static-files/
> During development, if you use django.contrib.staticfiles, this will be done automatically by runserver when DEBUG is set to True (see django.contrib.staticfiles.views.serve()).
This method is grossly inefficient and probably insecure, so it is unsuitable for production.

現状ではDEBUGがtrueだから`runserver`したときに同一サーバとして動いてるだけで、実際の本番環境では別サーバとしてデプロイしろとのこと。
だから、本番での運用については考え直さないといけないかな。

**Comment by tronperidot** [comment]
やっぱり同一ってダメなのか。
そうしたら親としてNginxを立てて、リバースプロキシで集約させるようにした方がいいんかな

**Comment by h-haraguchi** [comment]
で、Djangoにて静的ファイルをserveさせる方法は以下のページで3パターン提示されてる。
https://docs.djangoproject.com/en/2.1/howto/static-files/deployment/
> Serving the site and your static files from the same server
> Serving static files from a dedicated server
> Serving static files from a cloud service or CDN

今回のパターンだと Serving the site and your static files from the same server (同じサーバでserveする)が無難だね。
結局静的ファイルをDjangoのWebアプリケーションでserveできないならそもそもreact側で作成した静的ファイルを移動する必要ないだろうなと感じてる。
しかし、Djangoのadminも使うとなるとadminで使用している静的ファイルもserveする必要がある。
だから、react側で作成した静的ファイルとDjangoのadminで使う静的ファイルは最終的に同じディレクトリに置くほうがいいかな。
Djangoには`collectstatic`というコマンドがあって、静的ファイルを特定のディレクトリに集める機能がある。
`collectstatic`が集めるディレクトリはいろいろなんだけど、react側で作成した静的ファイルも集約対象にできるかどうかを今調査してまーす。

**Comment by h-haraguchi** [comment]
> そうしたら親としてNginxを立てて、リバースプロキシで集約させるようにした方がいいんかな

せやな。まぁミドルウェアの勉強にもなるんじゃない？ｗ
@takashi1coq がミドルウェア担当になるとかどうすか。

**Comment by h-haraguchi** [comment]
https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-STATICFILES_DIRS
`STATICFILES_DIRS`に`BASE_DIR`からの相対パス指定したら集約対象にできたわ。
静的ファイルの集約に関しては問題なさそう。

HTMLもreactの成果物を使うだろうから、Django側に作ってるscreenアプリは必要なくなるかな。

あとはNginxやね。

**Comment by takashi1coq** [comment]
> @takashi1coq がミドルウェア担当になるとかどうすか。

Nginxの勉強すればいいっすか

**Comment by h-haraguchi** [comment]
せやな

**Comment by tronperidot** [comment]
Nginxのほうが俺は好きだからそっちを上げただけで別にApacheでもいいよー
そこまで分散を意識するほどリクエスト飛ばないだろうし、DjangoのほうがApacheの方が楽にできるよとも言ってるし
お任せします！

**Comment by h-haraguchi** [comment]
https://github.com/tamakon/junk-t/issues/17#issuecomment-415970196 の通り、Nginxと通信する仕組み使うことにしたからNginx勉強でオナシャスｗ

**Comment by h-haraguchi** [comment]
本件は、Nginxにフロントの成果物を取ってきてもらうことになったため、Djangoでの手段は考える必要がなくなった。そのため、完了とします。
