### ISSUE TITLE
DBのテーブル構成

### ISSUE THREAD

**Issue by tronperidot** [tamakon/junk-t#15]
1st Release はこれがあればいいかなってレベルの内容です。

※シーケンスの部分は省略。全てのテーブルに追加でいいと思う

### User Table

| Field Name | Data | Note |
|:--|:--|:--|
| login_id | Integer | ログインするためのID |
| name | varchar | ユーザ名 |
| token | varchar |  ログイン後headerにつけるあれ。面倒でなければトークン用のテーブルでやる感じで |

- 権限とかは今は作らなくてもいい気がする

### Image Table
| Field Name | Data | Note |
|:--|:--|:--|
| tag | varchar | 画像の識別子。urlに置き換える際に使いたい |
| resource | blob or varchar (?) | 画像をファイルで保存するならいらない。形式はblobでもbase64でも |

### その他

原則としてココに書いてあることよりDjangoの流儀に従って貰って構いません。
過不足あったらオナシャス

**Comment by tronperidot** [comment]
image tableのresource fieldは画像をストレージに保存する場合は名前がurlとかにするべきかな

**Comment by h-haraguchi** [comment]
一応Userテーブルはadminのものを使い、Imageテーブルは作成したので完了とする。
