### ISSUE TITLE
必要なAPI

### ISSUE THREAD

**Issue by tronperidot** [tamakon/junk-t#16]
イメージです。作りやすさ重視で良いように変えちゃってください。
特に管理系はDjangoのを使うならそれに従うのが一番かと。
逆にreactで頑張る方針になったら再度検討します。

#### ログインAPI

/api/user/auth [POST]

request params

- id
- password

response params

```
{
  id: user.login_id,
  name: user.name,
  access_token: user.token
}
```

#### 画像一覧API
(権限必要)
/api/images [GET]

request params

response params

```
[
  {
    id: image.seq,
    tag: image.tag,
    url: SERVER_URL + '/' + 'resource path' + '/' + 'tag'
  }
  :
]
```

#### 画像保存API
(権限必要)
/api/images [POST]

request params

- tag
- file

response params

```
{}
```

#### 画像取得API

api(?)/resource/images/{tag} [GET]

request params

- tag

response

image file

一番の悩みどころ。imagesの階層に収めるなら
/api/images/tag/{tag}
とかなのかな？
apiのベストプラクティス的にはtag名称で取るならこれはqueryにするべき所だろうけど、そこまでする必要はないかなって思っている。

**Comment by h-haraguchi** [comment]
adminで実行できるものは作らなかったけど、必要なものは作ってマージした。完了とします！
