### ISSUE TITLE
Djangoの本番リリース方法を明確化する

### ISSUE THREAD

**Issue by h-haraguchi** [tamakon/junk-t#17]
現状ではローカル環境での起動方法しかREADMEに記述していない。
本番環境でのリリース方法を調査して記述する。
すべてコマンドで実現できそうだったら、自動化も検討する。

## 決めたいこと
- 本番環境のサーバをどのように構築するか(Dockerのコンテナでやるか、サーバそのものをしようするか)

## だいたい決まったこと
- 環境ごとの設定ファイルは分離して管理する
- NGINX-uWSGI-Djangoという形式で実現させる

**Comment by tronperidot** [comment]
> Djangoにはデフォルトで環境ごとの設定ファイルがないがどのように環境設定を分割するのか

https://docs.djangoproject.com/ja/2.1/topics/settings/#designating-the-settings
環境変数で設定ファイルを指定するみたいね。
実際に呼ばれているのはmanage.pyみたい。
そこで指定がなければデフォルトはserver.settingsを呼ぶような記述になってるね

**Comment by h-haraguchi** [comment]
https://docs.djangoproject.com/ja/2.1/howto/deployment/checklist/
リリース時に気をつけるべきこと、たくさんあったｗ

**Comment by h-haraguchi** [comment]
環境変数で設定ファイルを指定するってアプローチになると、デフォルトは今のようにserver.settingsを呼んで本番環境では別のファイルを呼ぶって言う感じになるかな。で、そうなってくると環境ごとで複数の設定ファイルが必要になるなぁと思い調べてみたら以下のパターンのアプローチがよく引っかかった。
https://medium.com/@ayarshabeer/django-best-practice-settings-file-for-multiple-environments-6d71c6966ee2
要はDjango御用達のsettingsファイルじゃなくてsettingsモジュールとして環境ごとに用意するって感じ。

https://github.com/sloria/environs
環境変数の取扱についてはこのライブラリが使えるかも。

**Comment by tronperidot** [comment]
でたwやっぱり設定モジュール作るのが推奨されるんだ

下の環境変数のやつはちゃんと見れてないけど、冗長になってかない？
なんか環境変数のマトリョーシカになりそうw

**Comment by h-haraguchi** [comment]
environsは通常の環境変数取得と比べて以下の利点があるのだそう。

> Why not os.environ?
> While os.environ is enough for simple use cases, a typical application will need a way to manipulate and validate raw environment variables. environs abstracts common tasks for handling environment variables.
> environs will help you
> - cast envvars to the correct type
> - specify required envvars
> - define default values
> - validate envvars
> - parse list and dict values
> - parse dates, datetimes, and timedeltas
> - parse proxied variables
> - serialize your configuration to JSON, YAML, etc.

まぁでも最初はこのライブラリなしでまずは設定ファイルの分離だけやってみるわ。

> 下の環境変数のやつはちゃんと見れてないけど、冗長になってかない？

ただでさえ設定ファイルで分離されてるのに、設定ファイルの環境変数定義ファイルまで環境ごとに分離したらまぁなかなか冗長だねｗ
設定ファイルと環境ごとの環境変数でどうにかするかな。

**Comment by h-haraguchi** [comment]
https://docs.djangoproject.com/ja/2.1/ref/django-admin/
以下`runserver`の説明
> DO NOT USE THIS SERVER IN A PRODUCTION SETTING. It has not gone through security audits or performance tests. (And that's how it's gonna stay. We're in the business of making Web frameworks, not Web servers, so improving this server to be able to handle a production environment is outside the scope of Django.)

ちょっと笑った。本番で使えないでやんのｗ
https://docs.djangoproject.com/ja/2.1/howto/deployment/
本番リリースではapacheの`mod_wsgi`を使ってデプロイするのが一番簡単らしい。
NginxとDjangoだけでのデプロイ方法が見つからん。多分DjangoのデプロイはNginx以外になにか噛ます必要有りげ。

**Comment by h-haraguchi** [comment]
https://pypi.org/project/mod_wsgi/
> This later mechanism for installing mod_wsgi using Python pip is a much simpler way of getting starting with hosting your Python web application.

Apacheの`mod_wsgi`モジュールは通常のApacheのインストールよりも`pip`を使用したインストールのほうが良いらしい。
他のページとかでもApacheのインストールの場合はインストールした`mod_wsgi`とPythonのバージョンが噛み合わなかったりして困ったとか言われてた。

で、この`mod_wsgi`の厄介なところは本番でしか使わないってことなんだよな。`pip install mod_wsgi`するならいっそPipfileに記述してしまおうかと思ったが、`pipenv`は環境ごとの分離には正式に対応してないんだな。`pipenv`のgithubのissue見ても環境変数を使用する解決案しかなかった。
Pipfileに入れたら入れたでMacとかではうまく動作しないらしいから厄介らしい。実際に単純にローカルで`pip install mod_wsgi`して`manage.py runmodwsgi`したら起動はしたけどlocalhost開かなかった。
とりあえず本番でしか使わないなら今はPipfileには入れないでおく。

**Comment by h-haraguchi** [comment]
現在、本番環境でのシミュレーションをDockerを使って実行中。
@takashi1coq  今回使うサーバってCentOSだっけ？

**Comment by h-haraguchi** [comment]
@tronperidot の助言を受けて、デプロイに関しては`uwsgi`を使うことにした。
Dockerの環境で現在立ち上げ確認中。

**Comment by h-haraguchi** [comment]
この課題の件、ちょっとスコープが大きすぎたかもしれん。
とりあえずDockerでuWSGIでの起動も一応できたし一旦は終わらせようかと思う。
いろいろと本番環境のための設定には課題が残ってるけど、別途課題を作って対応していこうと思ってる。
本番リリース方法について明確化されたことはあとでWikiに載せようと思います。
本番環境のOSについても別途どこかで明確化しよう。

**Comment by h-haraguchi** [comment]
一応Wikiを書いといた。Dockerはそもそも本番環境で使わず、WebアプリケーションとWebサーバの統合の確認のための環境として位置づける。
https://github.com/tamakon/junk-t/wiki/本番環境

本課題はWikiを書いたので完了とします。
