### ISSUE TITLE
画像情報取得apiの作成

### ISSUE THREAD

**Issue by tronperidot** [tamakon/junk-t#33]
tag, url, update_atあたりのパラメータが取れる一覧情報のapiがほしい

**Comment by h-haraguchi** [comment]
https://github.com/tamakon/junk-t/tree/image-api で対応中。

@tronperidot update_at のフォーマットはどんな感じがいい？
デフォルトは `2018-09-16T19:48:20.928111+09:00` みたいな感じで使う側でのパーシングが面倒くさそう。
あと、urlは実際に画像の内容を取得するAPIのurlでおけ？

**Comment by tronperidot** [comment]
@h-haraguchi 
標準のjsのDate使わないでmomentでやるつもりなんで、形式はそれで大丈夫っす
urlもそうだね！取得するフルパスだと嬉しいかな

**Comment by tronperidot** [comment]
@h-haraguchi 
urlもまだの認識でいいんよね？
ImageSerializer.pyを編集しているプルリクが見つからなかったので

**Comment by h-haraguchi** [comment]
まだ～。だけど粗削りで今できた。

**Comment by h-haraguchi** [comment]
まーじしたので完了
