### ISSUE TITLE
seedの作成

### ISSUE THREAD

**Issue by tronperidot** [tamakon/junk-t#44]
できれば管理ユーザであったり、メンバー一覧であったりコンテンツ用の画像であったりは初期データとして登録できるようにしたい。

**Comment by h-haraguchi** [comment]
資料発見。https://docs.djangoproject.com/en/2.1/howto/initial-data/
読みまぁす

**Comment by h-haraguchi** [comment]
superuserのseed作ったらパスワードが公開されちゃうと思ったけど、本番環境ではseed作成後にパスワードを変えればいいだけか。

**Comment by h-haraguchi** [comment]
`data migration`じゃなくて`Fixture`で全部まとめたいなと思ってて`superuser`はどうしようかなと調べてたらいいもの発見。https://stackoverflow.com/questions/34321075/how-to-add-superuser-in-django-from-fixture 。`dumpdata`良い。明後日辺りにやろう。

**Comment by tronperidot** [comment]
Fixtureいいね。
superuserは出来る限り推測されたくないからidもseedに残したくないかな。
なので、開発用のseedと本番用のseedが分かれてて、本番時にsuperuserは別途追加するのが良いかなって思ってる

**Comment by h-haraguchi** [comment]
本件、メンバー一覧とかの初期データはまだ作ってないけど #43 #42 とかで一緒に対応する予定です。
初期データを入れる手段が明確になったので本件は完了します。
