### ISSUE TITLE
Docker環境でフロントの静的ファイルをnginxから参照できるようにする

### ISSUE THREAD

**Issue by h-haraguchi** [tamakon/junk-t#61]
reactで作成された成果物をnginxから参照できるようにするために`collectstatic`の対象を追加する。

**Comment by h-haraguchi** [comment]
@tronperidot  `/client/build/static` 配下を`collectstatic`の対象にしたんだが、index.htmlとかservice-worker.jsとかはどうしようか迷ってる。
多分、http://localhost:8000/ で index.html に遷移できるようにnginxを設定することになるから、それに従って index.html と同ディレクトリにstaticディレクトリがある状態が好ましい。
djangoのadminの静的リソースとの整合性をあわせるためには`collectstatic`はあまり適役じゃないかもな。

**Comment by h-haraguchi** [comment]
<img width="577" alt="2018-10-17 22 41 52" src="https://user-images.githubusercontent.com/6197504/47090494-00fadf00-d25e-11e8-9ede-ff8d74e11132.png">
表示できたけどなんか違うものが出てきたｗｗｗ

**Comment by h-haraguchi** [comment]
これ、結局build配下だけじゃなくてsrcとかも全部必要って落ちかもしれんな。

**Comment by tronperidot** [comment]
service-worker.jsはpwaのためのものだから、今の所はreact create appが勝手に作っているもんだから多分なくても問題ないかな。

**Comment by h-haraguchi** [comment]
本件、Docker側の構成はnginx,django,node,mysqlでやることにしたのでやめまぁす
