### ISSUE TITLE
今あるソースをぶっ壊す！

### ISSUE THREAD

**Issue by tronperidot** [tamakon/junk-t#8]
サーバサイドがDjango、フロントエンドをreactでやることにしたので、今あるソースを削除する！！！

**Comment by h-haraguchi** [comment]
[2018-08-05-議事録](https://github.com/tamakon/junk-t/wiki/2018-08-05-議事録) 参照。

**Comment by takashi1coq** [comment]
最初↓のでやってみたけど、リベースからんでんだか、よくわかんないtmpできたから最終的にはrmしてpush -f した

http://ktykwsk.com/%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%ABpush%E3%81%97%E3%81%9F%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%84%E3%83%87%E3%82%A3%E3%83%AC%E3%82%AF%E3%83%88%E3%83%AA%E3%82%92%E5%89%8A/

**Comment by takashi1coq** [comment]
新しくコミットするに当たってよくわかんないエラー出なかったら閉じて

**Comment by tronperidot** [comment]
あざっす！！
